/* Jaano service worker — generated by scripts/build-pwa.mjs. Do not edit. */
const VERSION = 'jaano-vmt19ncfh';
const BASE = '/foodwise-india';
const SHELL = VERSION + '-shell';
const DATA = VERSION + '-data';
const IMAGES = VERSION + '-img';

// The app shell. Next emits hashed chunk filenames we cannot know here, so the
// shell precache is deliberately minimal (document + catalog + icons) and the
// hashed assets are cached at runtime on first use. That keeps install fast and
// never fails the whole install because one guessed URL 404'd.
const PRECACHE = [
  BASE + '/',
  BASE + '/manifest.webmanifest',
  BASE + '/icons/icon-192.png',
  BASE + '/icons/icon-512.png',
];
// The catalog is precached into the DATA cache, NOT the shell: the runtime
// handler below reads it from DATA, and putting it in the shell instead left a
// cache-name mismatch that made the app hang forever on the loading screen when
// opened offline.
const PRECACHE_DATA = [BASE + '/data/catalog.json'];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL);
    // addAll() is atomic — one failure discards everything. Cache individually
    // so a single missing asset cannot block the install.
    await Promise.all(PRECACHE.map((url) =>
      cache.add(new Request(url, { cache: 'reload' })).catch(() => {})
    ));
    const data = await caches.open(DATA);
    await Promise.all(PRECACHE_DATA.map((url) =>
      data.add(new Request(url, { cache: 'reload' })).catch(() => {})
    ));
    self.skipWaiting();
  })());
});

/**
 * THE FIRST-VISIT GAP: Next emits hashed chunk names that this file cannot know,
 * and on the very first load those chunks are requested BEFORE the worker
 * controls the page — so nothing caches them and the app cannot hydrate offline.
 * The page therefore reports the assets it actually loaded and we cache them
 * explicitly. Without this, an installed Jaano opens to a permanent spinner the
 * first time it is used without signal.
 */
self.addEventListener('message', (event) => {
  const data = event.data || {};
  if (data.type === 'SKIP_WAITING') { self.skipWaiting(); return; }
  if (data.type !== 'CACHE_ASSETS' || !Array.isArray(data.urls)) return;
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL);
    await Promise.all(data.urls.map(async (url) => {
      try {
        if (await cache.match(url)) return;
        await cache.add(new Request(url, { cache: 'no-cache' }));
      } catch { /* one bad asset must not fail the rest */ }
    }));
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => !k.startsWith(VERSION)).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

const isImage = (url) =>
  /\.(png|jpg|jpeg|webp|svg|gif|avif)$/i.test(url.pathname) ||
  url.hostname === 'images.openfoodfacts.org';

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);

  // Never cache the Open Food Facts API: a stale product record is worse than a
  // failed lookup, and offLookup.js already keeps its own scan cache with an
  // explicit offline path.
  if (url.hostname === 'world.openfoodfacts.org') return;

  // NAVIGATION — network first, fall back to the cached shell so the app opens
  // inside a shop with no signal.
  if (req.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        const cache = await caches.open(SHELL);
        cache.put(BASE + '/', fresh.clone());
        return fresh;
      } catch {
        const cached = await caches.match(BASE + '/', { ignoreSearch: true });
        return cached || Response.error();
      }
    })());
    return;
  }

  // CATALOG — stale-while-revalidate. The app renders instantly from cache and
  // silently upgrades to a corrected catalog in the background.
  if (url.pathname.endsWith('/data/catalog.json')) {
    event.respondWith((async () => {
      const cache = await caches.open(DATA);
      const cached = await cache.match(req, { ignoreSearch: true });
      const network = fetch(req).then((res) => {
        if (res && res.ok) cache.put(req, res.clone());
        return res;
      }).catch(() => null);
      return cached || (await network) || Response.error();
    })());
    return;
  }

  // PRODUCT IMAGES — cache first; they are immutable and expensive on mobile data.
  if (isImage(url)) {
    event.respondWith((async () => {
      const cache = await caches.open(IMAGES);
      const cached = await cache.match(req);
      if (cached) return cached;
      try {
        const res = await fetch(req);
        if (res && (res.ok || res.type === 'opaque')) cache.put(req, res.clone());
        return res;
      } catch {
        return cached || Response.error();
      }
    })());
    return;
  }

  // BUILD ASSETS (hashed JS/CSS) — cache first, since the filename changes on
  // every deploy and old entries are dropped by the version sweep on activate.
  if (url.origin === self.location.origin && url.pathname.includes('/_next/')) {
    event.respondWith((async () => {
      const cache = await caches.open(SHELL);
      const cached = await cache.match(req);
      if (cached) return cached;
      try {
        const res = await fetch(req);
        if (res && res.ok) cache.put(req, res.clone());
        return res;
      } catch {
        return Response.error();
      }
    })());
  }
});
