#!/usr/bin/env node
/**
 * Writes `public/manifest.webmanifest` and `public/sw.js` with the correct
 * basePath baked in.
 *
 * WHY GENERATED RATHER THAN STATIC: the app is served from `/` locally but from
 * `/foodwise-india/` on GitHub Pages, and neither a web manifest nor a service
 * worker goes through Next's basePath rewriting — both contain absolute URLs
 * that must already be right. Hard-coding either one breaks the other
 * environment, so both are emitted from the same PAGES_BASE flag the build uses.
 *
 * Run automatically by `npm run build` / `npm run deploy-build`.
 */
import { writeFile, mkdir } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const base = process.env.PAGES_BASE === '1' ? '/foodwise-india' : ''

// Bumping this invalidates the whole precache. It is stamped at build time so
// every deploy ships a new worker and clients pick the update up.
const VERSION = `jaano-v${Date.now().toString(36)}`

const manifest = {
  name: 'Jaano — Know what you eat',
  short_name: 'Jaano',
  description:
    'Scan any Indian packaged food and see what is really inside it: every additive decoded, '
    + 'organ-level impact, and how it fits your own health conditions.',
  start_url: `${base}/`,
  scope: `${base}/`,
  display: 'standalone',
  orientation: 'portrait',
  background_color: '#fbf9f4',
  theme_color: '#22372e',
  lang: 'en-IN',
  categories: ['health', 'food', 'lifestyle', 'medical'],
  icons: [
    { src: `${base}/icons/icon-192.png`, sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: `${base}/icons/icon-512.png`, sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: `${base}/icons/maskable-192.png`, sizes: '192x192', type: 'image/png', purpose: 'maskable' },
    { src: `${base}/icons/maskable-512.png`, sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
  shortcuts: [
    {
      name: 'Scan a barcode',
      short_name: 'Scan',
      description: 'Point the camera at a pack and get its verdict',
      url: `${base}/?view=barcode`,
      icons: [{ src: `${base}/icons/icon-192.png`, sizes: '192x192' }],
    },
    {
      name: 'My food diary',
      short_name: 'Diary',
      url: `${base}/?view=diary`,
      icons: [{ src: `${base}/icons/icon-192.png`, sizes: '192x192' }],
    },
  ],
}

const sw = `/* Jaano service worker — generated by scripts/build-pwa.mjs. Do not edit. */
const VERSION = '${VERSION}';
const BASE = '${base}';
const SHELL = VERSION + '-shell';
const DATA = VERSION + '-data';
const IMAGES = VERSION + '-img';

// The app shell. Next emits hashed chunk filenames we cannot know here, so the
// shell precache is deliberately minimal (document + catalog + icons) and the
// hashed assets are cached at runtime on first use. That keeps install fast and
// never fails the whole install because one guessed URL 404'd.
const PRECACHE = [
  BASE + '/',
  BASE + '/manifest.webmanifest',
  BASE + '/icons/icon-192.png',
  BASE + '/icons/icon-512.png',
];
// The catalog is precached into the DATA cache, NOT the shell: the runtime
// handler below reads it from DATA, and putting it in the shell instead left a
// cache-name mismatch that made the app hang forever on the loading screen when
// opened offline.
const PRECACHE_DATA = [BASE + '/data/catalog.json'];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL);
    // addAll() is atomic — one failure discards everything. Cache individually
    // so a single missing asset cannot block the install.
    await Promise.all(PRECACHE.map((url) =>
      cache.add(new Request(url, { cache: 'reload' })).catch(() => {})
    ));
    const data = await caches.open(DATA);
    await Promise.all(PRECACHE_DATA.map((url) =>
      data.add(new Request(url, { cache: 'reload' })).catch(() => {})
    ));
    self.skipWaiting();
  })());
});

/**
 * THE FIRST-VISIT GAP: Next emits hashed chunk names that this file cannot know,
 * and on the very first load those chunks are requested BEFORE the worker
 * controls the page — so nothing caches them and the app cannot hydrate offline.
 * The page therefore reports the assets it actually loaded and we cache them
 * explicitly. Without this, an installed Jaano opens to a permanent spinner the
 * first time it is used without signal.
 */
self.addEventListener('message', (event) => {
  const data = event.data || {};
  if (data.type === 'SKIP_WAITING') { self.skipWaiting(); return; }
  if (data.type !== 'CACHE_ASSETS' || !Array.isArray(data.urls)) return;
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL);
    await Promise.all(data.urls.map(async (url) => {
      try {
        if (await cache.match(url)) return;
        await cache.add(new Request(url, { cache: 'no-cache' }));
      } catch { /* one bad asset must not fail the rest */ }
    }));
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => !k.startsWith(VERSION)).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

const isImage = (url) =>
  /\\.(png|jpg|jpeg|webp|svg|gif|avif)$/i.test(url.pathname) ||
  url.hostname === 'images.openfoodfacts.org';

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);

  // Never cache the Open Food Facts API: a stale product record is worse than a
  // failed lookup, and offLookup.js already keeps its own scan cache with an
  // explicit offline path.
  if (url.hostname === 'world.openfoodfacts.org') return;

  // NAVIGATION — network first, fall back to the cached shell so the app opens
  // inside a shop with no signal.
  if (req.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        const cache = await caches.open(SHELL);
        cache.put(BASE + '/', fresh.clone());
        return fresh;
      } catch {
        const cached = await caches.match(BASE + '/', { ignoreSearch: true });
        return cached || Response.error();
      }
    })());
    return;
  }

  // CATALOG — stale-while-revalidate. The app renders instantly from cache and
  // silently upgrades to a corrected catalog in the background.
  if (url.pathname.endsWith('/data/catalog.json')) {
    event.respondWith((async () => {
      const cache = await caches.open(DATA);
      const cached = await cache.match(req, { ignoreSearch: true });
      const network = fetch(req).then((res) => {
        if (res && res.ok) cache.put(req, res.clone());
        return res;
      }).catch(() => null);
      return cached || (await network) || Response.error();
    })());
    return;
  }

  // PRODUCT IMAGES — cache first; they are immutable and expensive on mobile data.
  if (isImage(url)) {
    event.respondWith((async () => {
      const cache = await caches.open(IMAGES);
      const cached = await cache.match(req);
      if (cached) return cached;
      try {
        const res = await fetch(req);
        if (res && (res.ok || res.type === 'opaque')) cache.put(req, res.clone());
        return res;
      } catch {
        return cached || Response.error();
      }
    })());
    return;
  }

  // BUILD ASSETS (hashed JS/CSS) — cache first, since the filename changes on
  // every deploy and old entries are dropped by the version sweep on activate.
  if (url.origin === self.location.origin && url.pathname.includes('/_next/')) {
    event.respondWith((async () => {
      const cache = await caches.open(SHELL);
      const cached = await cache.match(req);
      if (cached) return cached;
      try {
        const res = await fetch(req);
        if (res && res.ok) cache.put(req, res.clone());
        return res;
      } catch {
        return Response.error();
      }
    })());
  }
});
`

await mkdir(path.join(root, 'public'), { recursive: true })
await writeFile(path.join(root, 'public', 'manifest.webmanifest'), JSON.stringify(manifest, null, 2))
await writeFile(path.join(root, 'public', 'sw.js'), sw)
console.log(`PWA files written (base="${base || '/'}", version=${VERSION})`)
